export const EDIT_TASK = "EDIT_TASK"

export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST"
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"

export const FETCH_ADDING_TASK_REQUEST = "FETCH_ADDING_TASK_REQUEST"
export const FETCH_ADDING_TASK_SUCCESS = "FETCH_ADDING_TASK_SUCCESS"
export const FETCH_ADDING_TASK_FAILURE = "FETCH_ADDING_TASK_FAILURE"

export const FETCH_FINISH_EDITING_TASK_REQUEST = "FETCH_FINISH_EDITING_TASK_REQUEST"
export const FETCH_FINISH_EDITING_TASK_SUCCESS = "FETCH_FINISH_EDITING_TASK_SUCCESS"
export const FETCH_FINISH_EDITING_TASK_FAILURE = "FETCH_FINISH_EDITING_TASK_FAILURE"

export const FETCH_DELETING_TASK_REQUEST = "FETCH_DELETING_TASK_REQUEST"
export const FETCH_DELETING_TASK_SUCCESS = "FETCH_DELETING_TASK_SUCCESS"
export const FETCH_DELETING_TASK_FAILURE = "FETCH_DELETING_TASK_FAILURE"

export const FETCH_DONE_TASK_REQUEST = "FETCH_DONE_TASK_REQUEST"
export const FETCH_DONE_TASK_SUCCESS = "FETCH_DONE_TASK_SUCCESS"
export const FETCH_DONE_TASK_FAILURE = "FETCH_DONE_TASK_FAILURE"

export const FETCH_FAILURE = "FETCH_FAILURE"
export const FETCH_SPECIFICALLY_TASKS_SUCCESS = "FETCH_SPECIFICALLY_TASKS_SUCCESS"
